/**
 *
 * @author Ezrael Powell, Zachary Reents, Roman Sepeda
 */
import java.io.*;
import java.net.Socket;
import java.util.Scanner;

public class DormMSJFrame extends javax.swing.JFrame {
    
    public int numStudents = 0;

    /**
     * Creates new form DormMSJFrame
     */
    public DormMSJFrame() {
        
        initComponents();
        
        student1.setVisible(false);
        student2.setVisible(false);
        student3.setVisible(false);
        student4.setVisible(false);
        student5.setVisible(false);
        student6.setVisible(false);
        student7.setVisible(false);
        student8.setVisible(false);
        student9.setVisible(false);
        student10.setVisible(false);
        student11.setVisible(false);
        student12.setVisible(false);
        
        student1Name.setVisible(false);
        student2Name.setVisible(false);
        student3Name.setVisible(false);
        student4Name.setVisible(false);
        student5Name.setVisible(false);
        student6Name.setVisible(false);
        student7Name.setVisible(false);
        student8Name.setVisible(false);
        student9Name.setVisible(false);
        student10Name.setVisible(false);
        student11Name.setVisible(false);
        student12Name.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addStudentWindow = new javax.swing.JDialog();
        firstNamePrompt = new javax.swing.JLabel();
        lastNamePrompt = new javax.swing.JLabel();
        genderPrompt = new javax.swing.JLabel();
        majorPrompt = new javax.swing.JLabel();
        firstNameResponse = new javax.swing.JTextField();
        lastNameResponse = new javax.swing.JTextField();
        genderResponse = new javax.swing.JTextField();
        majorResponse = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        removeStudentWindow = new javax.swing.JDialog();
        firstNameRemovePrompt = new javax.swing.JLabel();
        lastNameRemovePrompt = new javax.swing.JLabel();
        genderRemovePrompt = new javax.swing.JLabel();
        majorRemovePrompt = new javax.swing.JLabel();
        firstNameResponse1 = new javax.swing.JTextField();
        lastNameResponse1 = new javax.swing.JTextField();
        genderResponse1 = new javax.swing.JTextField();
        majorResponse1 = new javax.swing.JTextField();
        removeSubmitButton = new javax.swing.JButton();
        removeTitle = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        addStudent = new javax.swing.JButton();
        removeStudent = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        dormLayout = new javax.swing.JLabel();
        student12 = new javax.swing.JLabel();
        student10 = new javax.swing.JLabel();
        student7 = new javax.swing.JLabel();
        student11 = new javax.swing.JLabel();
        student9 = new javax.swing.JLabel();
        student1 = new javax.swing.JLabel();
        student8 = new javax.swing.JLabel();
        student3 = new javax.swing.JLabel();
        student5 = new javax.swing.JLabel();
        student6 = new javax.swing.JLabel();
        student2 = new javax.swing.JLabel();
        student4 = new javax.swing.JLabel();
        student1Name = new javax.swing.JLabel();
        student2Name = new javax.swing.JLabel();
        student3Name = new javax.swing.JLabel();
        student4Name = new javax.swing.JLabel();
        student5Name = new javax.swing.JLabel();
        student6Name = new javax.swing.JLabel();
        student12Name = new javax.swing.JLabel();
        student11Name = new javax.swing.JLabel();
        student10Name = new javax.swing.JLabel();
        student8Name = new javax.swing.JLabel();
        student9Name = new javax.swing.JLabel();
        student7Name = new javax.swing.JLabel();
        dormStatus = new javax.swing.JLabel();

        addStudentWindow.setMinimumSize(new java.awt.Dimension(400, 300));
        addStudentWindow.setSize(new java.awt.Dimension(400, 300));

        firstNamePrompt.setText("Enter the first name: ");

        lastNamePrompt.setText("Enter the last name: ");

        genderPrompt.setText("Enter the gender (M or F):");

        majorPrompt.setText("Enter the major: ");

        genderResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderResponseActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Add a student:");

        javax.swing.GroupLayout addStudentWindowLayout = new javax.swing.GroupLayout(addStudentWindow.getContentPane());
        addStudentWindow.getContentPane().setLayout(addStudentWindowLayout);
        addStudentWindowLayout.setHorizontalGroup(
            addStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStudentWindowLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(addStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStudentWindowLayout.createSequentialGroup()
                        .addComponent(majorPrompt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(majorResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addStudentWindowLayout.createSequentialGroup()
                        .addGroup(addStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNamePrompt)
                            .addComponent(firstNamePrompt)
                            .addComponent(genderPrompt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(addStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addStudentWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submitButton)
                    .addComponent(jLabel1))
                .addGap(159, 159, 159))
        );
        addStudentWindowLayout.setVerticalGroup(
            addStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addStudentWindowLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameResponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNamePrompt))
                .addGap(34, 34, 34)
                .addGroup(addStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNamePrompt)
                    .addComponent(lastNameResponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(addStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderPrompt)
                    .addComponent(genderResponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(addStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(majorPrompt)
                    .addComponent(majorResponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(submitButton)
                .addGap(19, 19, 19))
        );

        removeStudentWindow.setMinimumSize(new java.awt.Dimension(400, 300));
        removeStudentWindow.setSize(new java.awt.Dimension(400, 300));

        firstNameRemovePrompt.setText("Enter the first name: ");

        lastNameRemovePrompt.setText("Enter the last name: ");

        genderRemovePrompt.setText("Enter the gender (M or F):");

        majorRemovePrompt.setText("Enter the major: ");

        firstNameResponse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameResponse1ActionPerformed(evt);
            }
        });

        genderResponse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderResponse1ActionPerformed(evt);
            }
        });

        removeSubmitButton.setText("Submit");
        removeSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSubmitButtonActionPerformed(evt);
            }
        });

        removeTitle.setText("Remove a student:");

        javax.swing.GroupLayout removeStudentWindowLayout = new javax.swing.GroupLayout(removeStudentWindow.getContentPane());
        removeStudentWindow.getContentPane().setLayout(removeStudentWindowLayout);
        removeStudentWindowLayout.setHorizontalGroup(
            removeStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeStudentWindowLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(removeStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeStudentWindowLayout.createSequentialGroup()
                        .addComponent(majorRemovePrompt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(majorResponse1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removeStudentWindowLayout.createSequentialGroup()
                        .addGroup(removeStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameRemovePrompt)
                            .addComponent(firstNameRemovePrompt)
                            .addComponent(genderRemovePrompt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(removeStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameResponse1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameResponse1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderResponse1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
            .addGroup(removeStudentWindowLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(removeSubmitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeStudentWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeTitle)
                .addGap(153, 153, 153))
        );
        removeStudentWindowLayout.setVerticalGroup(
            removeStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeStudentWindowLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(removeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removeStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameResponse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameRemovePrompt))
                .addGap(34, 34, 34)
                .addGroup(removeStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameRemovePrompt)
                    .addComponent(lastNameResponse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(removeStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderRemovePrompt)
                    .addComponent(genderResponse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(removeStudentWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(majorRemovePrompt)
                    .addComponent(majorResponse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(removeSubmitButton)
                .addGap(23, 23, 23))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(5000, 5000));

        title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        title.setText("Dorm Management System");
        title.setPreferredSize(new java.awt.Dimension(155, 50));

        addStudent.setText("Add Student");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        removeStudent.setText("Remove Student");
        removeStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudentActionPerformed(evt);
            }
        });

        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        dormLayout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/DormBuildingV2.png"))); // NOI18N

        student12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boy.png"))); // NOI18N

        student10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boy.png"))); // NOI18N

        student7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boy.png"))); // NOI18N

        student11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boy.png"))); // NOI18N

        student9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boy.png"))); // NOI18N

        student1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boy.png"))); // NOI18N

        student8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boy.png"))); // NOI18N

        student3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boy.png"))); // NOI18N

        student5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boy.png"))); // NOI18N

        student6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boy.png"))); // NOI18N

        student2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boy.png"))); // NOI18N

        student4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boy.png"))); // NOI18N

        student1Name.setText("Student 1");

        student2Name.setText("Student 2");

        student3Name.setText("Student 3");

        student4Name.setText("Student 4");

        student5Name.setText("Student 5");

        student6Name.setText("Student 6");

        student12Name.setText("Student 12");

        student11Name.setText("Student 11");

        student10Name.setText("Student 10");

        student8Name.setText("Student 8");

        student9Name.setText("Student 9");

        student7Name.setText("Student 7");

        dormStatus.setText("Status: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(addStudent))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(student3Name)
                            .addComponent(student2Name)
                            .addComponent(student1Name))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(student1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(student2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(student3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dormLayout)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(student7Name)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(student8Name)
                                    .addGap(18, 18, 18)
                                    .addComponent(student9Name))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(student7)
                                    .addGap(18, 18, 18)
                                    .addComponent(student8)
                                    .addGap(18, 18, 18)
                                    .addComponent(student9))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(student12)
                            .addComponent(student11)
                            .addComponent(student10))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(student10Name)
                            .addComponent(student11Name)
                            .addComponent(student12Name))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(removeStudent)
                                .addGap(63, 63, 63)
                                .addComponent(dormStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(student4)
                                        .addGap(18, 18, 18)
                                        .addComponent(student5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(student4Name)
                                        .addGap(18, 18, 18)
                                        .addComponent(student5Name)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(student6Name)
                                    .addComponent(student6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quit)
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(student12)
                            .addComponent(student12Name))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(student11)
                            .addComponent(student11Name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(student10)
                            .addComponent(student10Name)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dormLayout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(student1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(student1Name)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(student2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(student2Name)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(student3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(student3Name)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(student7)
                            .addComponent(student8)
                            .addComponent(student9)
                            .addComponent(student6)
                            .addComponent(student4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(student4Name)
                                    .addComponent(student5Name))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(student6Name)
                                    .addComponent(student7Name)
                                    .addComponent(student8Name)
                                    .addComponent(student9Name))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quit)
                            .addComponent(addStudent)
                            .addComponent(removeStudent)
                            .addComponent(dormStatus))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(student5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        
        addStudentWindow.setVisible(true);
        addStudent.setEnabled(false);
        removeStudent.setEnabled(false);
    }//GEN-LAST:event_addStudentActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        
        addStudent.setEnabled(true);
        removeStudent.setEnabled(true);
  
        final String SERVER_NAME = "localhost";
        
        try
        {
            Socket clientToServer = new Socket(SERVER_NAME, 38520);
            PrintWriter outToServer = new PrintWriter(
                clientToServer.getOutputStream());
            Scanner inFromServer = new Scanner(
                clientToServer.getInputStream());

            numStudents++;
            int choice = 1;


            outToServer.println(choice);
            String firstName = firstNameResponse.getText();
            String lastName = lastNameResponse.getText();
            char gender = genderResponse.getText().charAt(0);
            String major = majorResponse.getText();

            outToServer.println(firstName);
            outToServer.println(lastName);
            outToServer.println(gender);
            outToServer.println(major);
            outToServer.flush();

            String studentInfo = inFromServer.nextLine();
            addStudentWindow.setVisible(false);
            
            if (numStudents == 1)
            {
                student1.setVisible(true);
                student1Name.setVisible(true);
                student1Name.setText(firstName);
                dormStatus.setText("Status: Added student!");
            }
            else if (numStudents == 2)
            {
                student2.setVisible(true);
                student2Name.setVisible(true);
                student2Name.setText(firstName);
                dormStatus.setText("Status: Added student!");                
            }
            else if (numStudents == 3)
            {
                student3.setVisible(true);
                student3Name.setVisible(true);
                student3Name.setText(firstName);
                dormStatus.setText("Status: Added student!");
            }
            else if (numStudents == 4)
            {
                student4.setVisible(true);
                student4Name.setVisible(true);
                student4Name.setText(firstName);
                dormStatus.setText("Status: Added student!");
            }
            else if (numStudents == 5)
            {
                student5.setVisible(true);
                student5Name.setVisible(true);
                student5Name.setText(firstName);
                dormStatus.setText("Status: Added student!");
            }
            else if (numStudents == 6)
            {
                student6.setVisible(true);
                student6Name.setVisible(true);
                student6Name.setText(firstName);
                dormStatus.setText("Status: Added student!");
            }
            else if (numStudents == 7)
            {
                student7.setVisible(true);
                student7Name.setVisible(true);
                student7Name.setText(firstName);
                dormStatus.setText("Status: Added student!");
            }
            else if (numStudents == 8)
            {
                student8.setVisible(true);
                student8Name.setVisible(true);
                student8Name.setText(firstName);
                dormStatus.setText("Status: Added student!");
            }
            else if (numStudents == 9)
            {
                student9.setVisible(true);
                student9Name.setVisible(true);
                student9Name.setText(firstName);
                dormStatus.setText("Status: Added student!");
            }
            else if (numStudents == 10)
            {
                student10.setVisible(true);
                student10Name.setVisible(true);
                student10Name.setText(firstName);
                dormStatus.setText("Status: Added student!");
            }
            else if (numStudents == 11)
            {
                student11.setVisible(true);
                student11Name.setVisible(true);
                student11Name.setText(firstName);
                dormStatus.setText("Status: Added student!");
            }
            else if (numStudents == 12)
            {
                student12.setVisible(true);
                student12Name.setVisible(true);
                student12Name.setText(firstName);
                dormStatus.setText("Status: Added student!");
            }
            else
            {
                dormStatus.setText("Status: Dorm is full!");
            }
        }
        catch (IOException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void removeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudentActionPerformed
        removeStudentWindow.setVisible(true);
        addStudent.setEnabled(false);
        removeStudent.setEnabled(false);
    }//GEN-LAST:event_removeStudentActionPerformed

    private void genderResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderResponseActionPerformed

    private void genderResponse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderResponse1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderResponse1ActionPerformed

    private void removeSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSubmitButtonActionPerformed
        addStudent.setEnabled(true);
        removeStudent.setEnabled(true);

        
        final String SERVER_NAME = "localhost";
        
        try
        {
            numStudents--;
            int choice = 2;
            
            Socket clientToServer = new Socket(SERVER_NAME, 38520);
            PrintWriter outToServer = new PrintWriter(
                clientToServer.getOutputStream());
            Scanner inFromServer = new Scanner(
                clientToServer.getInputStream());

            outToServer.println(choice);
            String firstName = firstNameResponse1.getText();
            String lastName = lastNameResponse1.getText();
            char gender = genderResponse1.getText().charAt(0);
            String major = majorResponse1.getText();
            
            outToServer.println(firstName);
            outToServer.println(lastName);
            outToServer.println(gender);
            outToServer.println(major);
            outToServer.flush();
            
            String studentInfo = inFromServer.nextLine();
            
            if (firstName.equals(student1Name.getText()))
            {
                student1.setVisible(false);
                student1Name.setText(" ");
                dormStatus.setText("Status: Removed student");
            }
            else if (firstName.equals(student2Name.getText()))
            {
                student2.setVisible(false);
                student2Name.setText(" ");
                dormStatus.setText("Status: Removed student");
            }
            else if (firstName.equals(student3Name.getText()))
            {
                student3.setVisible(false);
                student3Name.setText(" ");
                dormStatus.setText("Status: Removed student");
            }
            else if (firstName.equals(student4Name.getText()))
            {
                student4.setVisible(false);
                student4Name.setText(" ");
                dormStatus.setText("Status: Removed student");
            }
            else if (firstName.equals(student5Name.getText()))
            {
                student5.setVisible(false);
                student5Name.setText(" ");
                dormStatus.setText("Status: Removed student");
            }
            else if (firstName.equals(student6Name.getText()))
            {
                student6.setVisible(false);
                student6Name.setText(" ");
                dormStatus.setText("Status: Removed student");
            }
            else if (firstName.equals(student7Name.getText()))
            {
                student7.setVisible(false);
                student7Name.setText(" ");
                dormStatus.setText("Status: Removed student");
            }
            else if (firstName.equals(student8Name.getText()))
            {
                student8.setVisible(false);
                student8Name.setText(" ");
                dormStatus.setText("Status: Removed student");
            }
            else if (firstName.equals(student9Name.getText()))
            {
                student9.setVisible(false);
                student9Name.setText(" ");
                dormStatus.setText("Status: Removed student");
            }
            else if (firstName.equals(student10Name.getText()))
            {
                student10.setVisible(false);
                student10Name.setText(" ");
                dormStatus.setText("Status: Removed student");
            }
            else if (firstName.equals(student11Name.getText()))
            {
                student11.setVisible(false);
                student11Name.setText(" ");
                dormStatus.setText("Status: Removed student");
            }
            else if (firstName.equals(student12Name.getText()))
            {
                student12.setVisible(false);
                student12Name.setText(" ");
                dormStatus.setText("Status: Removed student");
            }
            else
            {
                dormStatus.setText("Status: No student found");
            }
            removeStudentWindow.setVisible(false);
        }
        catch (IOException e)
        {
            System.err.println(e);
        } 
        
    }//GEN-LAST:event_removeSubmitButtonActionPerformed

    private void firstNameResponse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameResponse1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameResponse1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new DormMSJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudent;
    private javax.swing.JDialog addStudentWindow;
    private javax.swing.JLabel dormLayout;
    private javax.swing.JLabel dormStatus;
    private javax.swing.JLabel firstNamePrompt;
    private javax.swing.JLabel firstNameRemovePrompt;
    private javax.swing.JTextField firstNameResponse;
    private javax.swing.JTextField firstNameResponse1;
    private javax.swing.JLabel genderPrompt;
    private javax.swing.JLabel genderRemovePrompt;
    private javax.swing.JTextField genderResponse;
    private javax.swing.JTextField genderResponse1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastNamePrompt;
    private javax.swing.JLabel lastNameRemovePrompt;
    private javax.swing.JTextField lastNameResponse;
    private javax.swing.JTextField lastNameResponse1;
    private javax.swing.JLabel majorPrompt;
    private javax.swing.JLabel majorRemovePrompt;
    private javax.swing.JTextField majorResponse;
    private javax.swing.JTextField majorResponse1;
    private javax.swing.JButton quit;
    private javax.swing.JButton removeStudent;
    private javax.swing.JDialog removeStudentWindow;
    private javax.swing.JButton removeSubmitButton;
    private javax.swing.JLabel removeTitle;
    private javax.swing.JLabel student1;
    private javax.swing.JLabel student10;
    private javax.swing.JLabel student10Name;
    private javax.swing.JLabel student11;
    private javax.swing.JLabel student11Name;
    private javax.swing.JLabel student12;
    private javax.swing.JLabel student12Name;
    private javax.swing.JLabel student1Name;
    private javax.swing.JLabel student2;
    private javax.swing.JLabel student2Name;
    private javax.swing.JLabel student3;
    private javax.swing.JLabel student3Name;
    private javax.swing.JLabel student4;
    private javax.swing.JLabel student4Name;
    private javax.swing.JLabel student5;
    private javax.swing.JLabel student5Name;
    private javax.swing.JLabel student6;
    private javax.swing.JLabel student6Name;
    private javax.swing.JLabel student7;
    private javax.swing.JLabel student7Name;
    private javax.swing.JLabel student8;
    private javax.swing.JLabel student8Name;
    private javax.swing.JLabel student9;
    private javax.swing.JLabel student9Name;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
